version: '3.4'
services:
  api:
    build:
      context: .
      target: 'api'
    ports:
      - '8080:8080'
    environment:
      - MONGO_CONNECTION=mongodb://mongo:27017
    depends_on:
      - mongo

  seed:
    build:
      context: .
      target: 'seed'
    environment:
      - MONGO_CONNECTION=mongodb://mongo:27017
    depends_on:
      - mongo
    restart: no

  mongo:
    image: mongo:4.4.13
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
