version: '3.4'
services:
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: ['yarn', 'lerna', 'run', 'dev', '--scope', '@apps/api']
    environment:
      - MONGO_CONNECTION=mongodb://mongo:27017
    volumes:
      - ./:/app
    depends_on:
      - mongo

  seed:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: ['yarn', 'lerna', 'run', 'dev', '--scope', '@apps/seed']
    environment:
      - MONGO_CONNECTION=mongodb://mongo:27017
    volumes:
      - ./:/app
    depends_on:
      - mongo
    restart: no

  mongo:
    image: mongo:4.4.13
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
